# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 671)
        MainWindow.setMinimumSize(QtCore.QSize(801, 671))
        MainWindow.setMaximumSize(QtCore.QSize(801, 671))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 901, 691))
        self.main_frame.setStyleSheet("#main_frame{\n"
"background-color: rgb(66,133,244);\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.choose_frame = QtWidgets.QFrame(self.main_frame)
        self.choose_frame.setGeometry(QtCore.QRect(100, 200, 611, 311))
        self.choose_frame.setMinimumSize(QtCore.QSize(8, 0))
        self.choose_frame.setStyleSheet("#choose_frame{\n"
"background-color: rgb(244,180,0);\n"
"border-radius:15px;\n"
"}")
        self.choose_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_frame.setObjectName("choose_frame")
        self.choose_btn = QtWidgets.QPushButton(self.choose_frame)
        self.choose_btn.setGeometry(QtCore.QRect(470, 90, 93, 31))
        self.choose_btn.setStyleSheet("#choose_btn{\n"
"background-color: rgb(255,255,255);\n"
"    font: 57 10pt \"Google Sans\";\n"
"border-radius:7px;\n"
"}\n"
"#choose_btn:hover{\n"
"background-color:rgb(219,68,55);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.choose_btn.setObjectName("choose_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.choose_frame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 83, 221, 41))
        self.lineEdit.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.choose_label = QtWidgets.QLabel(self.choose_frame)
        self.choose_label.setGeometry(QtCore.QRect(20, 83, 171, 41))
        self.choose_label.setStyleSheet("#choose_label\n"
"{\n"
"    \n"
"    \n"
"    font: 57 14pt \"Google Sans\";\n"
"}")
        self.choose_label.setObjectName("choose_label")
        self.status_label = QtWidgets.QLabel(self.choose_frame)
        self.status_label.setGeometry(QtCore.QRect(20, 190, 141, 21))
        self.status_label.setStyleSheet("#status_label\n"
"{\n"
"    \n"
"    \n"
"    font: 57 14pt \"Google Sans\";\n"
"}")
        self.status_label.setObjectName("status_label")
        self.start_btn = QtWidgets.QPushButton(self.choose_frame)
        self.start_btn.setGeometry(QtCore.QRect(470, 190, 93, 31))
        self.start_btn.setStyleSheet("#start_btn{\n"
"background-color: rgb(255,255,255);\n"
"    font: 57 10pt \"Google Sans\";\n"
"border-radius:7px;\n"
"}\n"
"#start_btn:hover{\n"
"background-color:rgb(219,68,55);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.start_btn.setObjectName("start_btn")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.choose_frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 180, 221, 41))
        self.lineEdit_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.logo_label = QtWidgets.QLabel(self.main_frame)
        self.logo_label.setGeometry(QtCore.QRect(210, 60, 421, 71))
        self.logo_label.setStyleSheet("#logo_label{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-image: url(:/newPrefix/assets/dsc-uit---karachi-logo-x1 (1).png);\n"
"    background-color: rgba(255, 255, 255,40);\n"
"    background-image: url(:/newPrefix/dsc-uit---karachi-logo-x1 (1).png);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.dev_label = QtWidgets.QLabel(self.main_frame)
        self.dev_label.setGeometry(QtCore.QRect(350, 20, 151, 31))
        self.dev_label.setStyleSheet("#dev_label{    \n"
"    \n"
"    font: 75 14pt \"Google Sans\";\n"
"\n"
"}")
        self.dev_label.setObjectName("dev_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        self.menuDeveloped_By = QtWidgets.QMenu(self.menubar)
        self.menuDeveloped_By.setObjectName("menuDeveloped_By")
        self.menuWarnings = QtWidgets.QMenu(self.menubar)
        self.menuWarnings.setObjectName("menuWarnings")
        MainWindow.setMenuBar(self.menubar)
        self.actionRaheel_Siddiqui = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRaheel_Siddiqui.setIcon(icon)
        self.actionRaheel_Siddiqui.setObjectName("actionRaheel_Siddiqui")
        self.actionWarnings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/gg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarnings.setIcon(icon1)
        self.actionWarnings.setObjectName("actionWarnings")
        self.actionGitHub_Code = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Octocat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitHub_Code.setIcon(icon2)
        self.actionGitHub_Code.setObjectName("actionGitHub_Code")
        self.actionGet_the_Software = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/assets/gg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGet_the_Software.setIcon(icon3)
        self.actionGet_the_Software.setObjectName("actionGet_the_Software")
        self.menuDeveloped_By.addAction(self.actionRaheel_Siddiqui)
        self.menuWarnings.addAction(self.actionWarnings)
        self.menuWarnings.addAction(self.actionGitHub_Code)
        self.menubar.addAction(self.menuDeveloped_By.menuAction())
        self.menubar.addAction(self.menuWarnings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_btn.setText(_translate("MainWindow", "Select"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "CSV File Path.."))
        self.choose_label.setText(_translate("MainWindow", "Select CSV File:"))
        self.status_label.setText(_translate("MainWindow", "Event Link:"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Event Link"))
        self.dev_label.setText(_translate("MainWindow", "Developed By"))
        self.menuDeveloped_By.setTitle(_translate("MainWindow", "Developed By"))
        self.menuWarnings.setTitle(_translate("MainWindow", "Help"))
        self.actionRaheel_Siddiqui.setText(_translate("MainWindow", "Raheel Siddiqui"))
        self.actionWarnings.setText(_translate("MainWindow", "Warnings!"))
        self.actionGitHub_Code.setText(_translate("MainWindow", "GitHub Code"))
        self.actionGet_the_Software.setText(_translate("MainWindow", "Get the Software"))

import pics_main

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
