# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):

    def warnings_window(self):
        from warnings_window import  Ui_MainWindow
        
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 591)
        MainWindow.setMinimumSize(QtCore.QSize(611, 591))
        MainWindow.setMaximumSize(QtCore.QSize(611, 591))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 611, 591))
        self.main_frame.setStyleSheet("#main_frame{\n"
"background-color: rgb(66,133,244);\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.choose_frame = QtWidgets.QFrame(self.main_frame)
        self.choose_frame.setGeometry(QtCore.QRect(80, 180, 451, 301))
        self.choose_frame.setMinimumSize(QtCore.QSize(8, 0))
        self.choose_frame.setStyleSheet("#choose_frame{\n"
"background-color: rgb(244,180,0);\n"
"border-radius:15px;\n"
"}")
        self.choose_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_frame.setObjectName("choose_frame")
        self.choose_label = QtWidgets.QLabel(self.choose_frame)
        self.choose_label.setGeometry(QtCore.QRect(30, 40, 81, 51))
        self.choose_label.setStyleSheet("#choose_label\n"
"{\n"
"    \n"
"    \n"
"    font: 57 14pt \"Google Sans\";\n"
"}")
        self.choose_label.setObjectName("choose_label")
        self.login_btn = QtWidgets.QPushButton(self.choose_frame)
        self.login_btn.setGeometry(QtCore.QRect(260, 230, 93, 31))
        self.login_btn.setStyleSheet("#login_btn{\n"
"background-color: rgb(255,255,255);\n"
"    font: 57 10pt \"Google Sans\";\n"
"border-radius:7px;\n"
"}\n"
"#login_btn:hover{\n"
"background-color:rgb(219,68,55);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.choose_frame)
        self.lineEdit.setGeometry(QtCore.QRect(200, 50, 221, 31))
        self.lineEdit.setStyleSheet("border-radius:9px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("    font: 57 9pt \"Google Sans\";\n""border-radius:9px;\n")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.choose_frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 110, 221, 31))
        self.lineEdit_2.setStyleSheet("    font: 57 9pt \"Google Sans\";\n""border-radius:9px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pass_label = QtWidgets.QLabel(self.choose_frame)
        self.pass_label.setGeometry(QtCore.QRect(30, 100, 121, 51))
        self.pass_label.setStyleSheet("#pass_label\n"
"{\n"
"    \n"
"    \n"
"    font: 57 14pt \"Google Sans\";\n"
"}")
        self.pass_label.setObjectName("pass_label")
        self.uni_label = QtWidgets.QLabel(self.choose_frame)
        self.uni_label.setGeometry(QtCore.QRect(30, 170, 151, 21))
        self.uni_label.setStyleSheet("#uni_label\n"
"{\n"
"    \n"
"    \n"
"    font: 57 11pt \"Google Sans\";\n"
"}")
        self.uni_label.setObjectName("uni_label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.choose_frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 160, 221, 41))
        self.lineEdit_3.setStyleSheet("border-radius:9px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.logo_label = QtWidgets.QLabel(self.main_frame)
        self.logo_label.setGeometry(QtCore.QRect(100, 60, 421, 71))
        self.logo_label.setStyleSheet("#logo_label{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-image: url(:/newPrefix/assets/dsc-uit---karachi-logo-x1 (1).png);\n"
"    background-color: rgb(255, 255, 255,40);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.dev_label = QtWidgets.QLabel(self.main_frame)
        self.dev_label.setGeometry(QtCore.QRect(240, 20, 151, 31))
        self.dev_label.setStyleSheet("#dev_label{    \n"
"    \n"
"    font: 75 14pt \"Google Sans\";\n"
"\n"
"}")
        self.dev_label.setObjectName("dev_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        self.menuDeveloped_By = QtWidgets.QMenu(self.menubar)
        self.menuDeveloped_By.setObjectName("menuDeveloped_By")
        self.menuWarnings = QtWidgets.QMenu(self.menubar)
        self.menuWarnings.setObjectName("menuWarnings")
        MainWindow.setMenuBar(self.menubar)
        self.actionRaheel_Siddiqui = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/assets/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRaheel_Siddiqui.setIcon(icon)
        self.actionRaheel_Siddiqui.setObjectName("actionRaheel_Siddiqui")
        self.actionWarnings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/assets/gg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarnings.setIcon(icon1)
        self.actionWarnings.setObjectName("actionWarnings")
        self.actionGitHub_Code = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/assets/Octocat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitHub_Code.setIcon(icon2)
        self.actionGitHub_Code.setObjectName("actionGitHub_Code")
        self.actionGet_the_Software = QtWidgets.QAction(MainWindow)
        self.actionGet_the_Software.setIcon(icon1)
        self.actionGet_the_Software.setObjectName("actionGet_the_Software")
        self.menuDeveloped_By.addAction(self.actionRaheel_Siddiqui)
        self.menuWarnings.addAction(self.actionWarnings)
        self.menuWarnings.addAction(self.actionGitHub_Code)
        self.menuWarnings.addAction(self.actionGet_the_Software)
        self.menubar.addAction(self.menuDeveloped_By.menuAction())
        self.menubar.addAction(self.menuWarnings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionRaheel_Siddiqui.triggered.connect(self.goto_raheel)
        self.actionGitHub_Code.triggered.connect(self.goto_github)
        self.actionGet_the_Software.triggered.connect(self.get_software)
        self.actionWarnings.triggered.connect(self.warnings_window)
        self.login_btn.clicked.connect(self.Login)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_label.setText(_translate("MainWindow", "Email:"))
        self.login_btn.setText(_translate("MainWindow", "Save Data"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Enter Email"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " Enter Password"))
        self.pass_label.setText(_translate("MainWindow", "Password:"))
        self.uni_label.setText(_translate("MainWindow", "Uni_platform_Link:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", " https://dsc.community.dev/usman-institute-of-technology/"))
        self.dev_label.setText(_translate("MainWindow", "Developed By"))
        self.menuDeveloped_By.setTitle(_translate("MainWindow", "Developed By"))
        self.menuWarnings.setTitle(_translate("MainWindow", "Help"))
        self.actionRaheel_Siddiqui.setText(_translate("MainWindow", "Raheel Siddiqui"))
        self.actionWarnings.setText(_translate("MainWindow", "Warnings!"))
        self.actionGitHub_Code.setText(_translate("MainWindow", "GitHub Code"))
        self.actionGet_the_Software.setText(_translate("MainWindow", "Get the Software"))

    def message(self,message):

        a1= QMessageBox()
        a1.setWindowTitle("message!")
        a1.setText(message)
        a1.setIcon(QMessageBox.Information)
        a1.setStandardButtons(QMessageBox.Ok)
        x = a1.exec_()

    def main_window(self):
        from main_window import  Ui_MainWindow
        
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()


    def goto_raheel(self):
        webbrowser.open("https://github.com/rawheel")
    def goto_github(self):
        webbrowser.open("https://github.com/DSC-UIT-khi/Get-DSC-Platform-Extension")

    def get_software(self):
        webbrowser.open("https://drive.google.com/drive/folders/1A4LPBtP_gRaumanvV5p_oIDUvbsTDw0i?usp=sharing")

    def Login(self):
        self.email = self.lineEdit.text()
        self.password = self.lineEdit_2.text()
        self.Uni_platform_Link = self.lineEdit_3.text()
        self.save_info()

    def save_info(self):
        if len(self.email) == 0 or len(self.password)== 0 or len(self.Uni_platform_Link) == 0 :
            self.message("Enter Proper Information!")

        else:
            if "https:" not in self.Uni_platform_Link:
                self.message("Enter Proper Uni_platform_Link with https:")
            else:
                secret_info = open("py_files/secret_info.txt","w")
                secret_info.write(self.email+" ")
                secret_info.write(" "+self.password)
                secret_info.write(" "+self.Uni_platform_Link)
                secret_info.close()
                self.main_window()




import pics_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
